# Generated by Django 4.0.6 on 2022-07-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0008_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10),
        ),
    ]
